apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  namespace: prod
  labels: 
    app: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
        - name: nginx-prod
          image: narason/nginx:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
