apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-uat
  namespace: uat
  labels: 
    app: nginx-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-uat
  template:
    metadata:
      labels:
        app: nginx-uat
    spec:
      containers:
        - name: nginx-uat
          image: narason/nginx:1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
